Add missing solum/core and solum/utils package to distutils
Otherwise these subpackages are not installed (tested with Python 2.7.5).
Fixes this import error:

>>> import solum
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "solum/__init__.py", line 5, in <module>
    from .core import ClassFile, ClassError, ConstantType
ImportError: No module named core